# Generated by Django 5.2 on 2025-07-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_logo_task_subtask_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='describtion',
            new_name='description',
        ),
    ]
